### ISSUE TITLE
dont get this started :(

### ISSUE THREAD

**Issue by NatsuDragneelKl** [shareslake/cardanocli-js#3]
Hey,

I dont get this started. 

I'am running my cardano-node on ubuntu. 

with npm run test I get the error "execSync is not a function".

if I remove the typeof window !== "undefined" || stuff before require the script, it start to run but with the new error "throw new Error("httpProvider required")"

I think I do it the wrong way, would be great to get more infos about how I can start with this wrapper.

**Comment by sublayerio** [comment]
Hey @NatsuDragneelKl, I could be wrong, but I think this might be related to your node version. If you enter `node -v` in the cli, what's the output you're getting?

**Comment by NatsuDragneelKl** [comment]
Hey, wow thanks for this fast response :)

This is the output: v12.19.0

I used the version that described on the repo

**Comment by sublayerio** [comment]
I see, i just tested it on v12 and v14, got the same error. I'm just guessing here but try adjusting the test script in the package.json from `jest` to `jest --env=node` and run `npm run test` again. By doing this I got different errors regarding some env variables that you will be able to set by adding a `env` file to the root of the repo dir containing the environment variables the test script is expecting. (https://github.com/Berry-Pool/cardanocli-js/blob/main/test/index.test.js#L8-L11) By default Jest is executed with a window object since it's main focus is for browser js testing stuff.

**Comment by NatsuDragneelKl** [comment]
Oh, this looks better :) new errors but one step forward, thanks man!

**Comment by alessandrokonrad** [comment]
Hey, the problem is that Jest magically uses a window object. The cardanocli-js library was designed to be used in Node.js and JavaScript. That's why there are these if-statements, but it made it difficult to run the tests easily.

**Comment by NatsuDragneelKl** [comment]
Thanks for explaination, I've test something around and now understand this stuff :) 

Thanks for this work @alessandrokonrad 

Now I'am about to check some of your other repos. Great work!
