### ISSUE TITLE
Suggestion for Wallet Labelling

### ISSUE THREAD

**Issue by kardall** [shareslake/cardanocli-js#8]
To make this 'fully compatible with cntools', don't name the wallet files with the wallet name inside the /priv/wallet/ directory.

Example: WalletName = testwallet

Folder Structure:
./priv/wallet/testwallet

File Names:
testwallet.payment.addr
testwallet.payment.skey
testwallet.payment.vkey

Those filenames break CNTools so it lists the wallet as selectable, but it doesn't recognize the extra 'walletname.' part of the file.
So you have to rename all 6 files to allow it to function from within CNTools.

That way, you could just copy the wallet folder to an offline node, make the transactions and load them into the node to submit online without need for the signing keys being there. But as it is, CNTools won't recognize the wallets without renaming.

**Comment by alessandrokonrad** [comment]
I think it's a little bit more secure if the files have the wallet name included as well, since you could accidentaly move files around and suddenly you have a payment.addr somehwere, but you don't know where it is coming from. Makes the overviews also better.
But it is easy to convert the folder in the CNTools structure with a single command either in bash or Js. So you can move back and forth quickly.

**Comment by kardall** [comment]
the folder structure is the same as CNtools though, and the `priv/wallet/walletname/*.addr/.skey/.vkey` is the same as what CNtools does when you create a wallet or import a wallet with mnemonics.

Technically speaking, you are not supposed to have wallets just lying around on your nodes anyway but... I can see your viewpoint. It's not a big deal like you say, to just rename the files. Was just a suggestion :)

**Comment by alessandrokonrad** [comment]
Right, keys should be offline ideally, but there are cases, where you need the keys on the node. E.g. if you just play around with the testnet.
